package com.sportsclub.identity.domain.enums;

public enum NotificationType {
    ATHLETE_REGISTERED_TEAM,
    ATHLETE_REGISTERED_COMPETITION,
    ATHLETE_REGISTERED_EVENT,
    TRAINING_SCHEDULED,
    TRAINING_PERFORMANCE,
    EVENT_PERFORMANCE,
    EVENT_RESULT,
    COMPETITION_RESULT,
    FEE_PAID,
    TRAINING_MISSED,
    ATTENDANCE_REGISTERED,
    OVERDUE_FEE
}