export const appPaths = {
  home: "/",
  login: "/login",
  unauthorized: "/unauthorized",
  app: "/app",
  calendar: "/app/calendar",
  dashboard: "/app/dashboard",
  people: "/app/people",
  profile: "/app/profile",
  modalities: "/app/modalities",
  teams: "/app/teams",
  training: "/app/training",
  selfGuidedTraining: "/app/self-guided-training",
  competition: "/app/competition",
  event: "/app/event",
  finance: "/app/finance",
  sportsReport: "/app/sports-report",
  financeReport: "/app/finance-report",
  clubSettings: "/app/club-settings",
  notification: "/app/notification",
} as const;
